name: medusa_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  # State management packages
  # -------------------
  get: ^4.6.5
  # -------------------

  # Image picker packages
  #--------------------
  image_picker: ^0.8.6+4
  image_cropper: ^3.0.1
  uuid: ^3.0.7
  #--------------------

  # UI packages
  # -------------------
  adaptive_dialog: ^1.8.2
  settings_ui: ^2.0.2
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.2
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre

  # Miscellaneous packages
  # -------------------
  equatable: ^2.0.5
  copy_with_extension_gen: ^5.0.2
  # Storage packages
  # -------------------
  shared_preferences: ^2.0.18
  path_provider: ^2.0.13
  cached_network_image: ^3.2.3
  # -------------------

  google_fonts: ^4.0.3
  dio: ^5.0.1
#  dartz: ^0.10.1

  flutter: 
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.0
  custom_refresh_indicator: ^2.0.1
  multiple_result: ^4.0.0

dev_dependencies: 
  flutter_lints: ^2.0.1
  build_runner: any
  #  copy_with_extension_gen: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true

