name: medusa_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  # State management packages
  # -------------------
  get: ^4.6.5
  # -------------------
  google_fonts: ^4.0.3

  # UI packages
  # -------------------
  adaptive_dialog: ^1.8.2
  settings_ui: ^2.0.2
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.6

  # Storage packages
  # -------------------
  shared_preferences: ^2.0.17
  path_provider: ^2.0.12
  cached_network_image: ^3.2.3
  # -------------------

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true

