name: medusa_admin
version: 1.0.0+1
publish_to: none
description: A medusa store manager for mobile !.
environment: 
  sdk: '>=3.0.0 <3.10.2'

dependencies: 
  cupertino_icons: ^1.0.5
  # State management packages
  # -------------------
  get: ^4.6.5
  # -------------------

  # Image picker packages
  #--------------------
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  uuid: ^3.0.7
  #--------------------

  # UI packages
  # -------------------
  adaptive_dialog: ^1.9.0-no-macos.2
  settings_ui: ^2.0.2
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.6
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre

  # Miscellaneous packages
  # -------------------
  equatable: ^2.0.5

  # Storage packages
  # -------------------
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  # -------------------

  dio: ^5.1.2

  flutter:
    sdk: flutter
  multiple_result: ^5.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_speed_dial: ^7.0.0
  info_popup: ^3.0.4
  multiselect: ^0.1.0
  flutter_slidable: ^3.0.0
  package_info_plus: ^4.0.2
  flutter_animate: ^4.1.1+1
  flutter_localizations:
    sdk: flutter
  super_banners: ^0.0.1
  google_fonts: ^5.1.0
  copy_with_extension: ^5.0.3
  skeletonizer: ^0.7.0
  cherry_toast: ^1.3.1
  flag: ^7.0.0

dev_dependencies: 
  flutter_lints: ^2.0.1
  build_runner: any
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: MedusaIcons
      fonts:
        - asset: fonts/MedusaIcons.ttf
flutter_icons:
  remove_alpha_ios: true
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/medusa.png"
