name: Build Flutter APK's and iPA files

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Run flutter doctor
        run: flutter doctor -v
      - name: Run pub get and build runner
        run: |
          flutter pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: | 
          flutter build apk --split-per-abi --release
          flutter build apk --release
          cd build/app/outputs/flutter-apk
          for f in app*.apk; do mv "$f" "Medusa-Admin-$RELEASE_VERSION-$f"; done
          echo ls

      - name: Build iPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r Medusa-Admin.ipa Payload
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/Medusa-Admin.ipa"
          allowUpdates: true
#
#      - name: Upload a Build Artifact
#        uses: actions/upload-artifact@v3.1.0
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/
