name: Build Flutter APK's and iPA files

on:
  workflow_dispatch:
  push:
    branches:
      - "workflow"
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - name: Run flutter doctor
        run: flutter doctor -v
      - name: Run pub get and build runner
        run: |
          echo $GITHUB_REF
          flutter pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: | 
          flutter build apk --split-per-abi --release
          flutter build apk --release
          cd build/app/outputs/flutter-apk
          for f in app*.apk; do mv "$f" "Medusa-Admin-${GITHUB_REF#refs/*/}-$f"; done
          ls

      - name: Build iPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r Medusa-Admin-${GITHUB_REF#refs/*/}.ipa Payload
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk,build/ios/iphoneos/*.ipa"
          allowUpdates: true
          tag: ${{ github.ref }}
