name: Build Flutter APK's and iPA files

on:
  workflow_dispatch:
  push:
    tags:
    - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
          cache: true
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - name: Run flutter doctor
        run: flutter doctor -v
      - name: Run pub get and build runner
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Write google-services file for Android
        run: printf "${{ secrets.GOOGLE_SERVICE_ANDROID }}" > android/app/google-services.json
#      - name: Write firebase app id file for for iOS
#        uses: mobiledevops/secret-to-file-action@v1
#        with:
#          base64-encoded-secret: ${{ secrets.FIREBASE_APP_ID }}
#          filename: "firebase_app_id_file.json"
#          is-executable: false
#          working-directory: "ios/firebase_app_id_file.json"
#        run: printf "${{ secrets.FIREBASE_APP_ID }}" > ios/firebase_app_id_file.json
      - name: Write GoogleService-Info.plist file for iOS
        run: printf "${{ secrets.GOOGLE_INFO_PLIST_IOS }}" > ios/Runner/GoogleService-Info.plist
      - name : Write firebase options file
        run: printf "${{ secrets.FIREBASE_OPTIONS }}" > lib/firebase_options.dart
      - name: Build APK
        run: | 
          flutter build apk --release
          cd build/app/outputs/apk/release
          mv *.apk Medusa-Admin-${GITHUB_REF#refs/*/}.apk
      - name: Build iPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r Medusa-Admin-${GITHUB_REF#refs/*/}.ipa Payload
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/*.ipa"
          allowUpdates: true
